import { NextResponse } from "next/server";
import { Resend } from "resend";
import { supabaseAdmin } from "@/lib/supabase/admin";

type TimelineCode = "EPOB" | "ETD" | "COMPLETE_OPS";

type AppointmentRow = {
  id: string;
  vessel_name: string;
  created_at: string | null;
};

type TimelineRow = {
  appointment_id: string;
  event_type: TimelineCode;
  eta: string | null;
  ata: string | null;
  event_date?: string | null;
  event_time_text?: string | null;
};

const DEFAULT_TO = "sergioaita21@gmail.com";
const TZ = "America/Buenos_Aires";
const DEFAULT_FROM = "Vesselmanager <summary@report.antaresship.agency>";

function resolveRecipient(requested?: string) {
  const forced = process.env.VESSELMANAGER_FORCE_TO?.trim();
  if (forced) return forced;
  return requested?.trim() || DEFAULT_TO;
}

function resolveFromAddress() {
  return process.env.VESSELMANAGER_EMAIL_FROM?.trim() || process.env.EMAIL_FROM?.trim() || DEFAULT_FROM;
}

function isAuthorizedCronRequest(req: Request) {
  const secret = process.env.CRON_SECRET?.trim();
  if (!secret) return true;
  const auth = req.headers.get("authorization")?.trim();
  return auth === `Bearer ${secret}`;
}

function datePartsInTz(date: Date, timeZone: string) {
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).formatToParts(date);
  const year = parts.find((p) => p.type === "year")?.value ?? "";
  const month = parts.find((p) => p.type === "month")?.value ?? "";
  const day = parts.find((p) => p.type === "day")?.value ?? "";
  const hour = parts.find((p) => p.type === "hour")?.value ?? "00";
  const minute = parts.find((p) => p.type === "minute")?.value ?? "00";
  return {
    ymd: `${year}-${month}-${day}`,
    hhmm: `${hour}${minute}`,
    display: `${day} ${new Date(`${year}-${month}-${day}T00:00:00`).toLocaleString("en-US", { month: "short" })} ${hour}:${minute}`,
    sort: Number(hour) * 60 + Number(minute),
  };
}

function formatSubjectDate(date: Date) {
  return new Intl.DateTimeFormat("en-GB", {
    timeZone: TZ,
    year: "numeric",
    month: "long",
    day: "2-digit",
  }).format(date);
}

function parseAtaDate(row?: TimelineRow | null) {
  if (!row?.ata) return null;
  const d = new Date(row.ata);
  if (Number.isNaN(d.getTime())) return null;
  return d;
}

function buildReports(args: {
  appointments: AppointmentRow[];
  timelineRows: TimelineRow[];
  now: Date;
}) {
  const { appointments, timelineRows, now } = args;
  const byAppointment = new Map<string, AppointmentRow>();
  appointments.forEach((item) => byAppointment.set(item.id, item));
  const todayYmd = datePartsInTz(now, TZ).ymd;
  const entries: Array<{ sort: number; text: string }> = [];

  appointments.forEach((appointment) => {
    if (!appointment.created_at) return;
    const createdAt = new Date(appointment.created_at);
    if (Number.isNaN(createdAt.getTime())) return;
    const parts = datePartsInTz(createdAt, TZ);
    if (parts.ymd !== todayYmd) return;
    entries.push({
      sort: parts.sort,
      text: `${parts.hhmm} "Appointment Created" of '${appointment.vessel_name}'`,
    });
  });

  timelineRows.forEach((row) => {
    const appointment = byAppointment.get(row.appointment_id);
    if (!appointment) return;
    const ataDate = parseAtaDate(row);
    if (!ataDate) return;
    const parts = datePartsInTz(ataDate, TZ);
    if (parts.ymd !== todayYmd) return;
    if (row.event_type === "EPOB") {
      entries.push({
        sort: parts.sort,
        text: `${parts.hhmm} "EPOB confirmed - ${parts.display}" of '${appointment.vessel_name}'`,
      });
      return;
    }
    if (row.event_type === "ETD") {
      entries.push({
        sort: parts.sort,
        text: `${parts.hhmm} "ETD confirmed - ${parts.display}" of '${appointment.vessel_name}'`,
      });
      return;
    }
    entries.push({
      sort: parts.sort,
      text: `${parts.hhmm} "Completed Service Checklist - ${parts.display}" of '${appointment.vessel_name}'`,
    });
  });

  entries.sort((a, b) => a.sort - b.sort || a.text.localeCompare(b.text));
  const plainLines = [
    "Daily Vessel Manager - Registered Events (18:00)",
    "",
    "Appointments - First Pilot Boarding, Sailings and Completed Service Checklist of today",
    ...(entries.length ? entries.map((entry) => `- ${entry.text}`) : ["- none"]),
    "",
    "Automatically Generated by antaresship.agency.",
  ];
  const plain = plainLines.join("\n");

  const htmlList = entries.length
    ? entries.map((entry) => `<li>${entry.text}</li>`).join("")
    : "<li>none</li>";
  const html = `<!doctype html>
<html>
  <body style="margin:0;padding:0;background:#eef3ef;font-family:Arial,sans-serif;color:#1f2937;">
    <div style="max-width:760px;margin:20px auto;background:#ffffff;border:1px solid #d5e4d8;border-radius:10px;overflow:hidden;">
      <div style="padding:16px 20px;background:#1f3d2f;color:#ffffff;">
        <div style="font-size:26px;font-weight:700;line-height:1.2;">Daily Vessel Manager - Registered Events (18:00)</div>
      </div>
      <div style="padding:18px 20px;">
        <div style="font-size:16px;font-weight:700;background:#2f6b4f;color:#ffffff;padding:8px 12px;border-radius:6px;">
          Appointments - First Pilot Boarding, Sailings and Completed Service Checklist of today
        </div>
        <ul style="margin:12px 0 14px 18px;padding:0;line-height:1.55;">${htmlList}</ul>
        <div style="margin-top:16px;font-size:12px;color:#64748b;">Automatically Generated by antaresship.agency.</div>
      </div>
    </div>
  </body>
</html>`;

  return { plain, html };
}

async function sendEveningSummary(to: string) {
  const supabase = supabaseAdmin();
  const appointmentsRes = await supabase.from("appointments").select("id,vessel_name,created_at").order("created_at", { ascending: false });
  if (appointmentsRes.error) throw new Error(appointmentsRes.error.message);

  const appointments = (appointmentsRes.data || []) as AppointmentRow[];
  const appointmentIds = appointments.map((item) => item.id);

  let timelineRows: TimelineRow[] = [];
  if (appointmentIds.length > 0) {
    const timelineWithExtended = await supabase
      .from("appointment_timeline")
      .select("appointment_id,event_type,eta,ata,event_date,event_time_text")
      .in("appointment_id", appointmentIds)
      .in("event_type", ["EPOB", "ETD", "COMPLETE_OPS"]);

    const needsFallback =
      timelineWithExtended.error &&
      (timelineWithExtended.error.message.includes("event_date") || timelineWithExtended.error.message.includes("event_time_text"));
    const timelineRes = needsFallback
      ? await supabase
          .from("appointment_timeline")
          .select("appointment_id,event_type,eta,ata")
          .in("appointment_id", appointmentIds)
          .in("event_type", ["EPOB", "ETD", "COMPLETE_OPS"])
      : timelineWithExtended;

    if (timelineRes.error) throw new Error(timelineRes.error.message);
    timelineRows = (timelineRes.data || []) as TimelineRow[];
  }

  const now = new Date();
  const { plain, html } = buildReports({ appointments, timelineRows, now });
  const subject = `Antares Vessel-Manager Registered Events ${formatSubjectDate(now)} - 18:00 hrs`;

  if (!process.env.RESEND_API_KEY?.trim()) throw new Error("RESEND_API_KEY is not configured");
  const fromAddress = resolveFromAddress();
  if (!fromAddress) throw new Error("EMAIL_FROM (or VESSELMANAGER_EMAIL_FROM) is not configured");

  const resend = new Resend(process.env.RESEND_API_KEY);
  const emailResult = await resend.emails.send({
    from: fromAddress,
    to,
    subject,
    text: plain,
    html,
  });
  if (emailResult.error) throw new Error(emailResult.error.message);

  return {
    to,
    subject,
    emailId: emailResult.data?.id || null,
  };
}

export async function POST(req: Request) {
  if (!isAuthorizedCronRequest(req)) {
    return NextResponse.json({ ok: false, error: "Unauthorized" }, { status: 401 });
  }
  try {
    const body = (await req.json().catch(() => ({}))) as { to?: string };
    const to = resolveRecipient(body.to);
    const data = await sendEveningSummary(to);
    return NextResponse.json({ ok: true, data });
  } catch (error: unknown) {
    return NextResponse.json(
      { ok: false, error: error instanceof Error ? error.message : "Failed to send evening summary" },
      { status: 500 },
    );
  }
}

export async function GET(req: Request) {
  if (!isAuthorizedCronRequest(req)) {
    return NextResponse.json({ ok: false, error: "Unauthorized" }, { status: 401 });
  }
  try {
    const data = await sendEveningSummary(resolveRecipient());
    return NextResponse.json({ ok: true, data });
  } catch (error: unknown) {
    return NextResponse.json(
      { ok: false, error: error instanceof Error ? error.message : "Failed to send evening summary" },
      { status: 500 },
    );
  }
}
