// Predefined SOF event list used by shift interruptions and Running SOF editor.
export const PREDEFINED_EVENTS = [
  // =========================
  // ARRIVAL / NAVIGATION
  // =========================
  "EOSP – END OF SEA PASSAGE",
  "ARRIVED AT PILOT STATION",
  "ARRIVED AT PORT LIMITS",
  "ARRIVED TO CUSTOMARY ANCHORAGE",
  "ANCHOR DOWN",
  "ANCHOR UP",
  "DRIFTING",
  "COSP – COMMENCED SEA PASSAGE",

  // =========================
  // PILOTS / NAVIGATION CONTROL
  // =========================
  "PILOT ON BOARD",
  "PILOT OFF",
  "RIVER PILOT ON BOARD",
  "RIVER PILOT OFF",
  "PILOT EXCHANGE – ZONA COMUN",
  "PILOT EXCHANGE – RIVER / SEA",
  "AWAITING PILOT",
  "DELAY – COASTGUARD TRAFFIC RESTRICTION",
  "DELAY – CHANNEL RESERVATION",
  "DELAY – TIDAL WINDOW",

  // =========================
  // BERTHING / UNBERTHING
  // =========================
  "FIRST LINE ASHORE",
  "ALL FAST",
  "COMMENCE MOORING",
  "COMMENCE UNMOORING",
  "SAILED FROM BERTH",
  "SAILED FROM ANCHORAGE",
  "DEPARTED",

  // =========================
  // WAITING / DELAYS (COMMERCIAL CLARITY)
  // =========================
  "WAITING BERTH – TERMINAL CONGESTION",
  "WAITING BERTH – NO FREE BERTH",
  "WAITING BERTH – WEATHER RESTRICTION",
  "WAITING BERTH – TERMINAL INSTRUCTIONS",
  "WAITING – TERMINAL INSTRUCTIONS",
  "WAITING – CHARTERERS INSTRUCTIONS",
  "WAITING – CARGO",
  "WAITING – TIDE",
  "WAITING – WEATHER",

  // =========================
  // AUTHORITIES / FORMALITIES
  // =========================
  "FREE PRATIQUE GRANTED",
  "AUTHORITIES ON BOARD",
  "INWARD CLEARANCE GRANTED",
  "OUTWARD CLEARANCE GRANTED",
  "ARRIVAL FORMALITIES COMPLETED",
  "DEPARTURE FORMALITIES COMPLETED",

  // =========================
  // NOR / LAYTIME
  // =========================
  "NOTICE OF READINESS TENDERED",
  "NOTICE OF READINESS RE-TENDERED",
  "NOTICE OF READINESS ACCEPTED",
  "LAYTIME COMMENCED",

  // =========================
  // GANGWAY / ACCESS
  // =========================
  "GANGWAY IN POSITION",
  "SHORE GANGWAY PLACED",
  "LAUNCH ALONGSIDE",
  "LAUNCH DEPARTED",

  // =========================
  // SURVEYS / INSPECTIONS
  // =========================
  "HOLDS OPEN FOR INSPECTION",
  "HOLDS INSPECTED",
  "HOLDS PASSED",
  "HOLDS FAILED",
  "TANK INSPECTION",
  "TANKS ACCEPTED",
  "TANKS REJECTED",
  "DRAFT SURVEY",
  "FINAL DRAFT SURVEY",
  "CARGO CALCULATIONS COMPLETED / FIGURES AGREED",

  // =========================
  // SAFETY / CHECKS (KEEP THESE!)
  // =========================
  "SHIP / SHORE SAFETY CHECKLIST COMPLETED",
  "SAFETY MEETING",
  "GAS FREE CERTIFICATE GRANTED",
  "POLLUTION BOOM CONNECTED",
  "POLLUTION BOOM DISCONNECTED",

  // =========================
  // CONNECTIONS (TANKERS / BULK)
  // =========================
  "CARGO ARM CONNECTED",
  "CARGO ARM DISCONNECTED",
  "SHORELINE CONNECTED",
  "SHORELINE DISCONNECTED",
  "HOSE CONNECTED",
  "HOSE DISCONNECTED",
  "HOSE TEST PASSED",
  "HOSE TEST FAILED",

  // =========================
  // CARGO OPERATIONS – START / STOP
  // =========================
  "COMMENCED LOADING",
  "RESUMED LOADING",
  "SUSPENDED LOADING",
  "COMMENCED DISCHARGE",
  "RESUMED DISCHARGE",
  "SUSPENDED DISCHARGE",

  // =========================
  // CARGO OPERATIONS – DETAILS
  // =========================
  "LOADING BY LINE DISPLACEMENT",
  "LINE DISPLACEMENT – MEASUREMENTS",
  "SHIFTING BETWEEN HOLDS",
  "PLACING BULLDOZER IN HOLD",
  "REMOVING BULLDOZER FROM HOLD",
  "TRIMMING IN PROGRESS",
  "CHANGING SHORE TANKS",

  // =========================
  // COMPLETION – LOADING (SMART VARIANTS)
  // =========================
  "COMPLETED LOADING – REACHED MAX AUTHORIZED SAILING DRAFT",
  "COMPLETED LOADING – LIMITED BY MAX AUTHORIZED DRAFT",
  "COMPLETED LOADING – REACHED RIVER / CHANNEL DRAFT RESTRICTION",
  "COMPLETED LOADING – LIMITED BY TIDE / DRAFT WINDOW",

  "COMPLETED LOADING – AS PER STOWPLAN",
  "COMPLETED LOADING – AS PER FINAL CARGO PLAN",
  "COMPLETED LOADING – ALL NOMINATED CARGO LOADED",

  "COMPLETED LOADING – AS PER MASTER'S REQUEST",
  "COMPLETED LOADING – AS PER OWNERS' INSTRUCTIONS",
  "COMPLETED LOADING – AS PER CHARTERERS' INSTRUCTIONS",
  "COMPLETED LOADING – AS PER TERMINAL INSTRUCTIONS",

  "COMPLETED LOADING – SHORT LOADED DUE TO DRAFT RESTRICTIONS",
  "COMPLETED LOADING – SHORT LOADED DUE TO CARGO SHORTAGE",
  "COMPLETED LOADING – SHORT LOADED AS PER CHARTERERS' INSTRUCTIONS",
  "COMPLETED LOADING – SHORT LOADED DUE TO WEATHER / SAFETY",

  "COMPLETED LOADING – SUBJECT TO FINAL TRIMMING",
  "COMPLETED LOADING – PENDING FINAL DRAFT SURVEY",
  "COMPLETED LOADING – FIGURES TO BE CONFIRMED",

  // =========================
  // COMPLETION – DISCHARGE (LEAN)
  // =========================
  "COMPLETED DISCHARGE – ALL CARGO DISCHARGED",
  "COMPLETED DISCHARGE – HOLDS EMPTY AND CLEAN",

  // =========================
  // WEATHER / TERMINAL / FAILURES
  // =========================
  "WEATHER DELAY",
  "OPERATIONS SUSPENDED – WEATHER",
  "MANEUVER CANCELLED – WEATHER",
  "LOADING INTERRUPTED – WEATHER",

  "OPERATIONS INTERRUPTED – TERMINAL FAILURE",
  "OPERATIONS INTERRUPTED – CONVEYOR FAILURE",
  "OPERATIONS INTERRUPTED – EQUIPMENT FAILURE",
  "OPERATIONS INTERRUPTED – BY TERMINAL",

  // =========================
  // DOCUMENTATION / FINALIZATION
  // =========================
  "DOCUMENTS ONBOARD",
  "BILL OF LADING AVAILABLE",
  "DOCUMENTS FINALIZED",
  "CARGO DOCUMENTS SIGNED",

  // =========================
  // MISC (KEEP GENERIC BUT CONTROLLED)
  // =========================
  "STANDBY",
  "IDLE",
  "OTHER",
] as const;
